/* Movies numbers */
const SHORTS_TIME = 40;
const LARGE_VISIBLE_NUMBER = 12;
const MEDIUM_VISIBLE_NUMBER = 8;
const SMALL_VISIBLE_NUMBER = 5;
const STANDART_ADDITIONAL_NUMBER = 3;
const SMALL_ADDITIONAL_NUMBER = 2;
const MEDIUM_WINDOW_WIDTH = 769;
const SMALL_WINDOW_WIDTH = 481;

/* Server errors */
const BAD_REQUEST_ERROR = 400;
const UNATHORIZED_ERROR = 401;
const CONFLICT_ERROR = 409;
const SERVER_ERROR = 500;

export {
  SHORTS_TIME,
  LARGE_VISIBLE_NUMBER,
  MEDIUM_VISIBLE_NUMBER,
  SMALL_VISIBLE_NUMBER,
  STANDART_ADDITIONAL_NUMBER,
  SMALL_ADDITIONAL_NUMBER,
  MEDIUM_WINDOW_WIDTH,
  SMALL_WINDOW_WIDTH,
  BAD_REQUEST_ERROR,
  UNATHORIZED_ERROR,
  CONFLICT_ERROR,
  SERVER_ERROR
};